version: '3'
services:
  service:
    container_name: service
    build: .
    ports:
      - '5001:5001'
    depends_on:
      - database

  database:
    container_name: database
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: logs
    expose:
      - '5045'
    ports:
      - '5045:5045'
    command: -p 5045

  test_script:
    build:
      context: ./test_script
      dockerfile: Dockerfile
    depends_on:
      - service
